apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "prometheusalert.labels" . | indent 4 }}
  name: {{ template "prometheusalert.fullname" . }}
data:
  init.sql: |
{{ .Values.config.init_sql | indent 4 }}
  user.csv: |
{{ .Values.config.user_csv | indent 4 }}
