{{- if .Values.config.autoCreateSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheusalert.appconf.secret" . }}
stringData:
  app.conf: |
{{ .Values.config.app_conf | indent 4 }}
{{- end }}
